spring:
  profiles:
    active:
    - dev
  config:
    import:
    - optional:file:../.env[.properties]
  application:
    name: secureauth
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
  
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  show-actuator: true
  
logging:
  level:
    "[org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer]": ERROR
